### ISSUE TITLE
[Bug] Mail Responder recipient address not found in tags

### ISSUE THREAD

**Issue by jaysadat** [TheHive-Project/Cortex-Analyzers#860] opened 2020-09-16 03:52 UTC
### Request Type
Bug

### Work Environment
| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu

### Description
The Mailer Responder checks the tags list for the recipient mail address and ends up with  failure with message "recipient address not found in tags".

### Steps to Reproduce
1. Steps to reproduce the behavior:
2. Configure Mailer 1.0 Responder
3. Create Case
4. Create Tag: "mail:user@example.com"
5. Start Responder Mailer for this case.
6. Check Result of Responder for Error Message: recipient address not found in tags

### Complementary information
![image](https://user-images.githubusercontent.com/64073414/93290248-77743300-f81f-11ea-93c4-124d49365c38.png)

![image](https://user-images.githubusercontent.com/64073414/93290312-95419800-f81f-11ea-804e-59c29e6d5376.png)

**Comment by dadokkio** [comment] 2020-09-16 08:05
Probably duplicated of #847 , are you using thehive4?

**Comment by jaysadat** [comment] 2020-09-16 09:05
Yes. I am using Thehive4. The email shows in the tag but in a weird format. Don't know if that could be the issue.

**Comment by farmerkz** [comment] 2020-12-02 17:12
Same problem.
Apparently this is due to the fact that when the tag is saved, The Hive4 changes "mail:" to "mail="

My workaround: in mailer.py replace
`mail_tags = [t[5:] for t in tags if t.startswith("mail:")]`
to
`mail_tags = [t[5:] for t in tags if t.startswith("mail=")]`

**Comment by dadokkio** [comment] 2021-01-08 09:12
Closing because duplicate of #848

**Closed by dadokkio** 2021-01-08 09:12 UTC
